server:
  port: 5000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://idpserver.ap-south-1.elasticbeanstalk.com/oauth2/jwks
          issuer-uri: http://idpserver.ap-south-1.elasticbeanstalk.com

      
springdoc:
  swagger-ui:
    oauth:
      clientId: swagger
      use-pkce-with-authorization-code-grant: true

swagger:
  oauth2:
    authorization-uri: http://idpserver.ap-south-1.elasticbeanstalk.com/oauth2/authorize
    token-uri: http://idpserver.ap-south-1.elasticbeanstalk.com/oauth2/token

app:
  aws:
    s3:
      accessKey: AKIASU566SBMQVN3VF4W
      secretKey: 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
      region: ap-south-1
      bucketName: bugflu-data
