server:
  port: 5000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://idpserver.bugflu.com/oauth2/jwks
          issuer-uri: https://idpserver.bugflu.com

      
springdoc:
  swagger-ui:
    oauth:
      clientId: swagger
      use-pkce-with-authorization-code-grant: true

swagger:
  oauth2:
    authorization-uri: https://idpserver.bugflu.com/oauth2/authorize
    token-uri: https://idpserver.bugflu.com/oauth2/token


