server:
  port: 5000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://idpserver.ap-south-1.elasticbeanstalk.com/oauth2/jwks
          issuer-uri: http://idpserver.ap-south-1.elasticbeanstalk.com

app:
  aws:
    s3:
      accessKey: AKIASU566SBM2YISSVMM
      secretKey: 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
      region: ap-south-1
      bucketName: bugflu-data
      
springdoc:
  swagger-ui:
    oauth:
      clientId: swagger
      use-pkce-with-authorization-code-grant: true

swagger:
  oauth2:
    authorization-uri: http://idpserver.ap-south-1.elasticbeanstalk.com/oauth2/authorize
    token-uri: http://idpserver.ap-south-1.elasticbeanstalk.com/oauth2/token
