test:
  name: Test Cloud
  
server:
  port: 9090

logging:
  level:
    root: DEBUG
  org:
    hibernate:
      SQL: DEBUG
      type: TRACE
    springframework:
      security: DEBUG
      web: DEBUG
#//simplignostic
spring:
  security:
    oauth2:
     client:
       registration:
         google:
           provider: google
           client-id: 246411264163-fm3kcsbvmmmski7obhr4b6prij28pd7l.apps.googleusercontent.com 
           client-secret: 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
           scope: https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
           client-name: Sign in with Google
         github:
           provider: github
           client-id:  edb778fc55e695a12970
           client-secret: 666a7295fe59838624362f5522d38d94a762f509
           scope: user:email, read:user
           client-name: Sign in with GitHub
       provider:
         google:
           user-name-attribute: email
         github:
           user-name-attribute: login
