test:
  name: Test Cloud
  
server:
  port: 5000

logging:
  level:
    root: DEBUG
  org:
    hibernate:
      SQL: DEBUG
      type: TRACE
    springframework:
      security: DEBUG
      web: DEBUG
      
#//simplignostic
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://idpserver.ap-south-1.elasticbeanstalk.com/jwks
          issuer-uri: http://idpserver.ap-south-1.elasticbeanstalk.com
      client:
        registration:
          google:
            provider: google
            client-id: 246411264163-fm3kcsbvmmmski7obhr4b6prij28pd7l.apps.googleusercontent.com
            client-secret: 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
            scope: https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github:
            provider: github
            client-id:  edb778fc55e695a12970
            client-secret: 666a7295fe59838624362f5522d38d94a762f509
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login
app:
  mail:
    username: jainshashank562@gmail.com
    password: wpjfvcyonutyzdux
    host: smtp.gmail.com
    port: 587
    smtp: true
    tls: true
    debug: true
    testConnection: true

  security:
    login:
      max-count: 3

  jwt:
    encryptor:
      password: password
      salt: 626F6F746966756C
  secret:
    key: yVMO9QNJ5i2IBZLZCuJPGg==

  twilio:
    sid: AC0031223f42f5e05f9de55ca055f53928
    token: b69d149400b0a077c3077c2daa5c800c
    phoneNo: +13083002653

  secure:
    token:
      expireAfter: 1800
    otp:
      expireAfter: 1800
      length: 6

  aws:
    s3:
      accessKey: AKIA4KKLS7OTUPTMNFVB
      secretKey: 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
      region: us-east-1
      bucketName: dd
